#!/usr/bin/python3
# -*- coding: utf-8 -*-
# SpaceX raten 
# generated by Structorizer 3.32-06 
from enum import Enum
import math

print("Hallo SpaceX")
tabA = ["StarShip15", "StarShip10", "Booster7"]
a = 5
if (a > 5):
    print(a, "ist größer als 5!")
else:
    print("a zu klein")

for i in range(10, 100+1, 10):
    print("dies ist i:", i)

print("Ende von diesem Programm \n aber nicht von SpaceX!")
# TODO: No automatic loop translation found! 
for k in tabA:
    print(k)
