// program SpaceX raten 
// Generated by Structorizer 3.32-06 

#include <stdbool.h>



int main(void)
{
	// TODO: Check and accomplish variable declarations: 

	Print("Hallo SpaceX");
	a ==5;
	if (a > 5)
	{
		print(a, "ist größer als 5!");
	}
	else
	{
		print("a zu klein");
	}
	print("Ende von diesem Programm \n aber nicht von SpaceX!");

	return 0;
}
