#!/usr/bin/python3
# -*- coding: utf-8 -*-
# SpaceX raten 
# generated by Structorizer 3.32-06 
from enum import Enum
import math

print("Hallo SpaceX")
a = 5
if (a > 5):
    print(a, "ist größer als 5!")
else:
    print("a zu klein")

print("Ende von diesem Programm \n aber nicht von SpaceX!")
